import type { GroupMeta, Target } from '../types'

export const GROUPS: GroupMeta[] = [
  {
    key: 'mainland',
    label: '中国大陆',
    eyebrow: 'MAINLAND ROUTES',
    headline: '观察当前网络访问中国大陆主流入口的完成速度与稳定性。',
    description: '适合判断当前链路对常见本地服务的基础可达性与响应节奏。',
  },
  {
    key: 'global',
    label: '国际主流',
    eyebrow: 'GLOBAL STACK',
    headline: '观察当前网络接入全球常见开放互联网服务时的表现。',
    description: '适合快速判断外部网页、开发平台与公共基础设施的访问质量。',
  },
  {
    key: 'challenge',
    label: '困难目标',
    eyebrow: 'CHALLENGING TARGETS',
    headline: '观察在更容易出现波动的目标上，这条链路是否仍能完成访问。',
    description: '这些结果更适合作为异常提示，而不是绝对的底层网络结论。',
  },
]

export const TARGETS: Target[] = [
  {
    id: 'baidu-home',
    label: 'Baidu',
    group: 'mainland',
    probeType: 'image',
    url: 'https://www.baidu.com/img/flexible/logo/pc/result.png',
    logoUrl: 'https://www.baidu.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'load',
    location: 'CN · Search',
    tags: ['搜索', '门户'],
    emphasis: '适合观察本地网页入口是否快速直达。',
  },
  {
    id: 'qq-home',
    label: 'Tencent',
    group: 'mainland',
    probeType: 'image',
    url: 'https://mat1.gtimg.com/www/icon/favicon2.ico',
    logoUrl: 'https://mat1.gtimg.com/www/icon/favicon2.ico',
    timeoutMs: 6000,
    expectedSignal: 'load',
    location: 'CN · Platform',
    tags: ['综合平台', '门户'],
    emphasis: '适合观察大型综合站点的基础访问表现。',
  },
  {
    id: 'zhihu-favicon',
    label: 'Zhihu',
    group: 'mainland',
    probeType: 'image',
    url: 'https://static.zhihu.com/heifetz/favicon.ico',
    logoUrl: 'https://static.zhihu.com/heifetz/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'load',
    location: 'CN · Community',
    tags: ['社区', '内容'],
    emphasis: '适合观察内容社区类站点的资源加载速度。',
  },
  {
    id: 'bilibili-favicon',
    label: 'Bilibili',
    group: 'mainland',
    probeType: 'image',
    url: 'https://www.bilibili.com/favicon.ico',
    logoUrl: 'https://www.bilibili.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'load',
    location: 'CN · Video',
    tags: ['视频', '娱乐'],
    emphasis: '适合观察高访问量媒体站点的静态资源触达情况。',
  },
  {
    id: 'jd-favicon',
    label: 'JD',
    group: 'mainland',
    probeType: 'image',
    url: 'https://www.jd.com/favicon.ico',
    logoUrl: 'https://www.jd.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'load',
    location: 'CN · Commerce',
    tags: ['电商', '交易'],
    emphasis: '适合补充交易类网站的首跳资源检测。',
  },
  {
    id: 'github-favicon',
    label: 'GitHub',
    group: 'global',
    probeType: 'image',
    url: 'https://github.githubassets.com/favicons/favicon.png',
    logoUrl: 'https://github.githubassets.com/favicons/favicon.png',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Global · Dev',
    tags: ['开发', '协作'],
    emphasis: '适合观察全球开发平台的基础访问情况。',
  },
  {
    id: 'wikipedia-logo',
    label: 'Wikipedia',
    group: 'global',
    probeType: 'image',
    url: 'https://www.wikipedia.org/portal/wikipedia.org/assets/img/Wikipedia-logo-v2.png',
    logoUrl: 'https://www.wikipedia.org/static/favicon/wikipedia.ico',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Global · Knowledge',
    tags: ['知识', '公共资源'],
    emphasis: '适合观察国际公共知识站点的稳定性。',
  },
  {
    id: 'cloudflare-cdn',
    label: 'Cloudflare',
    group: 'global',
    probeType: 'fetch',
    url: 'https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css',
    logoUrl: 'https://www.cloudflare.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['CDN', '基础设施'],
    emphasis: '适合判断公共 CDN 与 no-cors 资源链路是否可用。',
  },
  {
    id: 'openai-favicon',
    label: 'OpenAI',
    group: 'global',
    probeType: 'image',
    url: 'https://openai.com/favicon.ico',
    logoUrl: 'https://openai.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Global · AI',
    tags: ['AI', 'SaaS'],
    emphasis: '适合补充新一代 AI 服务访问能力的观察。',
  },
  {
    id: 'aws-home',
    label: 'AWS',
    group: 'global',
    probeType: 'image',
    url: 'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico',
    logoUrl: 'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Global · Cloud',
    tags: ['云平台', '基础设施'],
    emphasis: '适合观察大型云平台静态资源的访问表现。',
  },
  {
    id: 'google-favicon',
    label: 'Google',
    group: 'challenge',
    probeType: 'image',
    url: 'https://www.google.com/favicon.ico',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Challenge · Search',
    tags: ['搜索', '国际入口'],
    emphasis: '适合观察典型国际入口在当前链路下是否顺利完成响应。',
  },
  {
    id: 'youtube-favicon',
    label: 'YouTube',
    group: 'challenge',
    probeType: 'image',
    url: 'https://www.youtube.com/s/desktop/6d1d1102/img/favicon_32x32.png',
    logoUrl: 'https://www.youtube.com/s/desktop/6d1d1102/img/favicon_32x32.png',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Challenge · Video',
    tags: ['视频', '媒体'],
    emphasis: '适合观察媒体类国际服务的资源触达情况。',
  },
  {
    id: 'telegram-web',
    label: 'Telegram',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://web.telegram.org/',
    logoUrl: 'https://web.telegram.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Messaging',
    tags: ['通信', 'Web'],
    emphasis: '适合补充即时通信类 Web 服务的到达性观察。',
  },
  {
    id: 'x-favicon',
    label: 'X',
    group: 'challenge',
    probeType: 'image',
    url: 'https://abs.twimg.com/favicons/twitter.3.ico',
    logoUrl: 'https://abs.twimg.com/favicons/twitter.3.ico',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Challenge · Social',
    tags: ['社交', '实时信息'],
    emphasis: '适合观察社交入口的静态资源访问能力。',
  },
  {
    id: 'reddit-favicon',
    label: 'Reddit',
    group: 'challenge',
    probeType: 'image',
    url: 'https://www.redditstatic.com/shreddit/assets/favicon/32x32.png',
    logoUrl: 'https://www.redditstatic.com/shreddit/assets/favicon/32x32.png',
    timeoutMs: 7000,
    expectedSignal: 'load',
    location: 'Challenge · Community',
    tags: ['社区', '讨论'],
    emphasis: '适合补充国际讨论社区的访问情况。',
  },
]
