import type { GroupMeta, Target } from '../types'

export const GROUPS: GroupMeta[] = [
  {
    key: 'mainland',
    label: '中国大陆',
    eyebrow: 'MAINLAND ROUTES',
    headline: '观察当前网络访问中国大陆主流入口的完成速度与稳定性。',
    description: '适合判断当前链路对常见本地服务的基础可达性与响应节奏。',
  },
  {
    key: 'global',
    label: '国际主流',
    eyebrow: 'GLOBAL STACK',
    headline: '观察当前网络接入全球常见开放互联网服务时的表现。',
    description: '适合快速判断外部网页、开发平台与公共基础设施的访问质量。',
  },
  {
    key: 'challenge',
    label: '困难目标',
    eyebrow: 'CHALLENGING TARGETS',
    headline: '观察在更容易出现波动的目标上，这条链路是否仍能完成访问。',
    description: '这些结果更适合作为异常提示，而不是绝对的底层网络结论。',
  },
]

export const TARGETS: Target[] = [
  {
    id: 'baidu-home',
    label: 'Baidu',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.baidu.com/',
    logoUrl: 'https://www.baidu.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Search',
    tags: ['搜索', '门户'],
    emphasis: '适合观察本地网页入口是否快速直达。',
  },
  {
    id: 'qq-home',
    label: 'Tencent',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.qq.com/',
    logoUrl: '/brand-logos/tencent.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Platform',
    tags: ['综合平台', '门户'],
    emphasis: '适合观察大型综合站点的基础访问表现。',
  },
  {
    id: 'zhihu-favicon',
    label: 'Zhihu',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.zhihu.com/',
    logoUrl: 'https://static.zhihu.com/heifetz/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Community',
    tags: ['社区', '内容'],
    emphasis: '适合观察内容社区类站点的资源加载速度。',
  },
  {
    id: 'bilibili-favicon',
    label: 'Bilibili',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.bilibili.com/',
    logoUrl: 'https://www.bilibili.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Video',
    tags: ['视频', '娱乐'],
    emphasis: '适合观察高访问量媒体站点的静态资源触达情况。',
  },
  {
    id: 'jd-favicon',
    label: 'JD',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.jd.com/',
    logoUrl: 'https://www.jd.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Commerce',
    tags: ['电商', '交易'],
    emphasis: '适合补充交易类网站的首跳资源检测。',
  },
  {
    id: 'taobao-home',
    label: 'Taobao',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.taobao.com/',
    logoUrl: '/brand-logos/taobao.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Commerce',
    tags: ['电商', '消费'],
    emphasis: '适合补充大型消费平台首页资源的可达性观察。',
  },
  {
    id: 'weibo-home',
    label: 'Weibo',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://weibo.com/',
    logoUrl: '/brand-logos/weibo.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Social',
    tags: ['社交', '资讯'],
    emphasis: '适合补充热点资讯与社交入口的页面访问观测。',
  },
  {
    id: 'xiaohongshu-home',
    label: 'Xiaohongshu',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.xiaohongshu.com/',
    logoUrl: '/brand-logos/xiaohongshu.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Lifestyle',
    tags: ['生活方式', '社区'],
    emphasis: '适合补充移动社区与生活方式内容平台的触达情况。',
  },
  {
    id: 'github-favicon',
    label: 'GitHub',
    group: 'global',
    probeType: 'fetch',
    url: 'https://github.com/',
    logoUrl: '/brand-logos/github.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Dev',
    tags: ['开发', '协作'],
    emphasis: '适合观察全球开发平台的基础访问情况。',
  },
  {
    id: 'wikipedia-logo',
    label: 'Wikipedia',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.wikipedia.org/',
    logoUrl: 'https://www.wikipedia.org/static/favicon/wikipedia.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Knowledge',
    tags: ['知识', '公共资源'],
    emphasis: '适合观察国际公共知识站点的稳定性。',
  },
  {
    id: 'cloudflare-cdn',
    label: 'Cloudflare',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.cloudflare.com/',
    logoUrl: 'https://www.cloudflare.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['CDN', '基础设施'],
    emphasis: '适合判断公共 CDN 与 no-cors 资源链路是否可用。',
  },
  {
    id: 'openai-favicon',
    label: 'OpenAI',
    group: 'global',
    probeType: 'fetch',
    url: 'https://openai.com/',
    logoUrl: 'https://openai.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · AI',
    tags: ['AI', 'SaaS'],
    emphasis: '适合补充新一代 AI 服务访问能力的观察。',
  },
  {
    id: 'aws-home',
    label: 'AWS',
    group: 'global',
    probeType: 'fetch',
    url: 'https://aws.amazon.com/',
    logoUrl: 'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Cloud',
    tags: ['云平台', '基础设施'],
    emphasis: '适合观察大型云平台静态资源的访问表现。',
  },
  {
    id: 'apple-home',
    label: 'Apple',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.apple.com/',
    logoUrl: '/brand-logos/apple.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Consumer',
    tags: ['终端', '消费'],
    emphasis: '适合观察全球消费电子入口的基础资源访问表现。',
  },
  {
    id: 'microsoft-home',
    label: 'Microsoft',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.microsoft.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Platform',
    tags: ['平台', '软件'],
    emphasis: '适合补充综合平台与软件服务入口的网页触达观测。',
  },
  {
    id: 'stackoverflow-home',
    label: 'Stack Overflow',
    group: 'global',
    probeType: 'fetch',
    url: 'https://stackoverflow.com/',
    logoUrl: '/brand-logos/stackoverflow.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Dev',
    tags: ['开发', '问答'],
    emphasis: '适合补充开发问答社区的资源访问情况。',
  },
  {
    id: 'claude-home',
    label: 'Claude',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://claude.ai/',
    logoUrl: '/brand-logos/claude.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · AI',
    tags: ['AI', '助手'],
    emphasis: '适合观察受区域链路影响时，新一代 AI 助手入口是否仍能完成访问。',
  },
  {
    id: 'discord-home',
    label: 'Discord',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://discord.com/',
    logoUrl: '/brand-logos/discord.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Community',
    tags: ['社区', '通信'],
    emphasis: '适合补充实时社区与协作平台在当前链路下的到达性观察。',
  },
  {
    id: 'netflix-home',
    label: 'Netflix',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.netflix.com/',
    logoUrl: '/brand-logos/netflix.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Streaming',
    tags: ['流媒体', '娱乐'],
    emphasis: '适合补充国际流媒体服务在当前网络环境下的入口可达性观察。',
  },
  {
    id: 'google-favicon',
    label: 'Google',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Search',
    tags: ['搜索', '国际入口'],
    emphasis: '适合观察典型国际入口在当前链路下是否顺利完成响应。',
  },
  {
    id: 'youtube-favicon',
    label: 'YouTube',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.youtube.com/',
    logoUrl: '/brand-logos/youtube.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Video',
    tags: ['视频', '媒体'],
    emphasis: '适合观察媒体类国际服务的资源触达情况。',
  },
  {
    id: 'telegram-web',
    label: 'Telegram',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://web.telegram.org/',
    logoUrl: 'https://web.telegram.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Messaging',
    tags: ['通信', 'Web'],
    emphasis: '适合补充即时通信类 Web 服务的到达性观察。',
  },
  {
    id: 'x-favicon',
    label: 'X',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://x.com/',
    logoUrl: 'https://abs.twimg.com/favicons/twitter.3.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Social',
    tags: ['社交', '实时信息'],
    emphasis: '适合观察社交入口的静态资源访问能力。',
  },
  {
    id: 'reddit-favicon',
    label: 'Reddit',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.reddit.com/',
    logoUrl: '/brand-logos/reddit.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Community',
    tags: ['社区', '讨论'],
    emphasis: '适合补充国际讨论社区的访问情况。',
  }
]
