import type { GroupMeta, Target } from '../types'

export const GROUPS: GroupMeta[] = [
  {
    key: 'mainland',
    label: '中国大陆',
    eyebrow: 'MAINLAND ROUTES',
    headline: '观察当前网络访问中国大陆主流入口、平台服务与重点学术机构的完成速度与稳定性。',
    description: '适合判断当前链路对常见本地服务、科研高校与公共机构的基础可达性。',
  },
  {
    key: 'hmt',
    label: '港澳台',
    eyebrow: 'HK MO TW ROUTES',
    headline: '观察当前网络访问港澳台重点高校、科研机构与公共服务入口的表现。',
    description: '适合补充大中华区跨境链路、教育科研网络与区域门户的访问质量判断。',
  },
  {
    key: 'global',
    label: '国际主流',
    eyebrow: 'GLOBAL STACK',
    headline: '观察当前网络接入全球常见开放互联网、技术生态、CDN 与高声誉学术组织时的表现。',
    description: '适合快速判断外部网页、开发平台、公共基础设施与国际科研教育资源的访问质量。',
  },
  {
    key: 'gaming',
    label: '游戏娱乐',
    eyebrow: 'GAMING NETWORKS',
    headline: '观察当前网络访问国内外游戏平台、游戏发行商、直播与电竞服务入口的表现。',
    description: '适合判断游戏下载、账号平台、社区直播与游戏服务官网的基础触达质量。',
  },
  {
    key: 'challenge',
    label: '困难目标',
    eyebrow: 'CHALLENGING TARGETS',
    headline: '观察在更容易出现波动的目标上，这条链路是否仍能完成访问。',
    description: '这些结果更适合作为异常提示，而不是绝对的底层网络结论。',
  },
]

export const TARGETS: Target[] = [
  {
    id: 'baidu-home',
    label: 'Baidu',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.baidu.com/',
    logoUrl: 'https://www.baidu.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Search',
    tags: ['搜索', '门户'],
    emphasis: '适合观察本地网页入口是否快速直达。',
  },
  {
    id: 'qq-home',
    label: 'Tencent',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.qq.com/',
    logoUrl: '/brand-logos/tencent.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Platform',
    tags: ['综合平台', '门户'],
    emphasis: '适合观察大型综合站点的基础访问表现。',
  },
  {
    id: 'zhihu-favicon',
    label: 'Zhihu',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.zhihu.com/',
    logoUrl: 'https://static.zhihu.com/heifetz/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Community',
    tags: ['社区', '内容'],
    emphasis: '适合观察内容社区类站点的资源加载速度。',
  },
  {
    id: 'bilibili-favicon',
    label: 'Bilibili',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.bilibili.com/',
    logoUrl: 'https://www.bilibili.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Video',
    tags: ['视频', '娱乐'],
    emphasis: '适合观察高访问量媒体站点的静态资源触达情况。',
  },
  {
    id: 'jd-favicon',
    label: 'JD',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.jd.com/',
    logoUrl: 'https://www.jd.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Commerce',
    tags: ['电商', '交易'],
    emphasis: '适合补充交易类网站的首跳资源检测。',
  },
  {
    id: 'taobao-home',
    label: 'Taobao',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.taobao.com/',
    logoUrl: '/brand-logos/taobao.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Commerce',
    tags: ['电商', '消费'],
    emphasis: '适合补充大型消费平台首页资源的可达性观察。',
  },
  {
    id: 'weibo-home',
    label: 'Weibo',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://weibo.com/',
    logoUrl: '/brand-logos/weibo.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Social',
    tags: ['社交', '资讯'],
    emphasis: '适合补充热点资讯与社交入口的页面访问观测。',
  },
  {
    id: 'xiaohongshu-home',
    label: 'Xiaohongshu',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.xiaohongshu.com/',
    logoUrl: '/brand-logos/xiaohongshu.svg',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Lifestyle',
    tags: ['生活方式', '社区'],
    emphasis: '适合补充移动社区与生活方式内容平台的触达情况。',
  },
  {
    id: 'douyin-home',
    label: 'Douyin',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.douyin.com/',
    logoUrl: 'https://www.douyin.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Short Video',
    tags: ['短视频', '社交'],
    emphasis: '适合观察国内短视频平台入口的基础访问表现。',
  },
  {
    id: 'kuaishou-home',
    label: 'Kuaishou',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.kuaishou.com/',
    logoUrl: 'https://www.kuaishou.com/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Short Video',
    tags: ['短视频', '直播'],
    emphasis: '适合补充国内视频与直播入口的网页触达观察。',
  },
  {
    id: 'pku-home',
    label: 'Peking University',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.pku.edu.cn/',
    logoUrl: 'https://www.pku.edu.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · University',
    tags: ['高校', '北京'],
    emphasis: '适合观察北京大学官网入口的访问质量。',
  },
  {
    id: 'tsinghua-home',
    label: 'Tsinghua University',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.tsinghua.edu.cn/',
    logoUrl: 'https://www.tsinghua.edu.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · University',
    tags: ['高校', '北京'],
    emphasis: '适合观察清华大学官网入口的访问质量。',
  },
  {
    id: 'fudan-home',
    label: 'Fudan University',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.fudan.edu.cn/',
    logoUrl: 'https://www.fudan.edu.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · University',
    tags: ['高校', '上海'],
    emphasis: '适合观察复旦大学官网入口的访问质量。',
  },
  {
    id: 'sjtu-home',
    label: 'Shanghai Jiao Tong',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.sjtu.edu.cn/',
    logoUrl: 'https://www.sjtu.edu.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · University',
    tags: ['高校', '上海'],
    emphasis: '适合观察上海交通大学官网入口的访问质量。',
  },
  {
    id: 'zju-home',
    label: 'Zhejiang University',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.zju.edu.cn/',
    logoUrl: 'https://www.zju.edu.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · University',
    tags: ['高校', '浙江'],
    emphasis: '适合观察浙江大学官网入口的访问质量。',
  },
  {
    id: 'ustc-home',
    label: 'USTC',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.ustc.edu.cn/',
    logoUrl: 'https://www.ustc.edu.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · University',
    tags: ['高校', '科研'],
    emphasis: '适合观察中国科学技术大学官网入口的访问质量。',
  },
  {
    id: 'nju-home',
    label: 'Nanjing University',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.nju.edu.cn/',
    logoUrl: 'https://www.nju.edu.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · University',
    tags: ['高校', '江苏'],
    emphasis: '适合观察南京大学官网入口的访问质量。',
  },
  {
    id: 'cas-home',
    label: 'Chinese Academy of Sciences',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.cas.cn/',
    logoUrl: 'https://www.cas.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Research',
    tags: ['科研机构', '科学院'],
    emphasis: '适合观察中国科学院官网入口的科研网络可达性。',
  },
  {
    id: 'nsfc-home',
    label: 'NSFC',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.nsfc.gov.cn/',
    logoUrl: 'https://www.nsfc.gov.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Research Funding',
    tags: ['科研基金', '机构'],
    emphasis: '适合观察国家自然科学基金委入口的可达性。',
  },
  {
    id: 'moe-cn-home',
    label: 'MOE China',
    group: 'mainland',
    probeType: 'fetch',
    url: 'https://www.moe.gov.cn/',
    logoUrl: 'https://www.moe.gov.cn/favicon.ico',
    timeoutMs: 6000,
    expectedSignal: 'opaque',
    location: 'CN · Education',
    tags: ['教育', '机构'],
    emphasis: '适合观察中国教育部官网入口的访问表现。',
  },
  {
    id: 'hku-home',
    label: 'HKU',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.hku.hk/',
    logoUrl: 'https://www.hku.hk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'HK · University',
    tags: ['香港', '高校'],
    emphasis: '适合观察香港大学官网入口的跨境访问表现。',
  },
  {
    id: 'cuhk-home',
    label: 'CUHK',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.cuhk.edu.hk/',
    logoUrl: 'https://www.cuhk.edu.hk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'HK · University',
    tags: ['香港', '高校'],
    emphasis: '适合观察香港中文大学官网入口的访问质量。',
  },
  {
    id: 'hkust-home',
    label: 'HKUST',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://hkust.edu.hk/',
    logoUrl: 'https://hkust.edu.hk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'HK · University',
    tags: ['香港', '高校'],
    emphasis: '适合观察香港科技大学官网入口的访问质量。',
  },
  {
    id: 'cityu-home',
    label: 'CityUHK',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.cityu.edu.hk/',
    logoUrl: 'https://www.cityu.edu.hk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'HK · University',
    tags: ['香港', '高校'],
    emphasis: '适合观察香港城市大学官网入口的访问质量。',
  },
  {
    id: 'polyu-home',
    label: 'PolyU',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.polyu.edu.hk/',
    logoUrl: 'https://www.polyu.edu.hk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'HK · University',
    tags: ['香港', '高校'],
    emphasis: '适合观察香港理工大学官网入口的访问质量。',
  },
  {
    id: 'umac-home',
    label: 'University of Macau',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.um.edu.mo/',
    logoUrl: 'https://www.um.edu.mo/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'MO · University',
    tags: ['澳门', '高校'],
    emphasis: '适合观察澳门大学官网入口的访问质量。',
  },
  {
    id: 'ntu-tw-home',
    label: 'National Taiwan University',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.ntu.edu.tw/',
    logoUrl: 'https://www.ntu.edu.tw/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'TW · University',
    tags: ['台湾', '高校'],
    emphasis: '适合观察台湾大学官网入口的访问质量。',
  },
  {
    id: 'nthu-tw-home',
    label: 'National Tsing Hua University',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.nthu.edu.tw/',
    logoUrl: 'https://www.nthu.edu.tw/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'TW · University',
    tags: ['台湾', '高校'],
    emphasis: '适合观察台湾清华大学官网入口的访问质量。',
  },
  {
    id: 'academia-sinica-home',
    label: 'Academia Sinica',
    group: 'hmt',
    probeType: 'fetch',
    url: 'https://www.sinica.edu.tw/',
    logoUrl: 'https://www.sinica.edu.tw/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'TW · Research',
    tags: ['台湾', '科研机构'],
    emphasis: '适合观察台湾中央研究院官网入口的科研网络可达性。',
  },
  {
    id: 'github-favicon',
    label: 'GitHub',
    group: 'global',
    probeType: 'fetch',
    url: 'https://github.com/',
    logoUrl: '/brand-logos/github.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Dev',
    tags: ['开发', '协作'],
    emphasis: '适合观察全球开发平台的基础访问情况。',
  },
  {
    id: 'wikipedia-logo',
    label: 'Wikipedia',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.wikipedia.org/',
    logoUrl: 'https://www.wikipedia.org/static/favicon/wikipedia.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Knowledge',
    tags: ['知识', '公共资源'],
    emphasis: '适合观察国际公共知识站点的稳定性。',
  },
  {
    id: 'cloudflare-cdn',
    label: 'Cloudflare',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.cloudflare.com/',
    logoUrl: 'https://www.cloudflare.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['CDN', '基础设施'],
    emphasis: '适合判断公共 CDN 与 no-cors 资源链路是否可用。',
  },
  {
    id: 'openai-favicon',
    label: 'OpenAI',
    group: 'global',
    probeType: 'fetch',
    url: 'https://openai.com/robots.txt',
    logoUrl: 'https://openai.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · AI',
    tags: ['AI', 'SaaS'],
    emphasis: '适合补充新一代 AI 服务静态入口的连通性观察。',
  },
  {
    id: 'aws-home',
    label: 'AWS',
    group: 'global',
    probeType: 'fetch',
    url: 'https://aws.amazon.com/',
    logoUrl: 'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Cloud',
    tags: ['云平台', '基础设施'],
    emphasis: '适合观察大型云平台静态资源的访问表现。',
  },
  {
    id: 'apple-home',
    label: 'Apple',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.apple.com/',
    logoUrl: '/brand-logos/apple.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Consumer',
    tags: ['终端', '消费'],
    emphasis: '适合观察全球消费电子入口的基础资源访问表现。',
  },
  {
    id: 'microsoft-home',
    label: 'Microsoft',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.microsoft.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Platform',
    tags: ['平台', '软件'],
    emphasis: '适合补充综合平台与软件服务入口的网页触达观测。',
  },
  {
    id: 'stackoverflow-home',
    label: 'Stack Overflow',
    group: 'global',
    probeType: 'fetch',
    url: 'https://stackoverflow.com/',
    logoUrl: '/brand-logos/stackoverflow.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Dev',
    tags: ['开发', '问答'],
    emphasis: '适合补充开发问答社区的资源访问情况。',
  },
  {
    id: 'python-downloads',
    label: 'Python',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.python.org/downloads/',
    logoUrl: 'https://www.python.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Runtime',
    tags: ['Python', '下载'],
    emphasis: '适合观察 Python 官网与下载入口的访问表现。',
  },
  {
    id: 'pypi-simple',
    label: 'PyPI',
    group: 'global',
    probeType: 'fetch',
    url: 'https://pypi.org/simple/',
    logoUrl: 'https://pypi.org/static/images/favicon.35549fe8.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Package',
    tags: ['Python', '包源'],
    emphasis: '适合观察 pip 默认包索引入口的浏览器侧触达表现。',
  },
  {
    id: 'npm-registry',
    label: 'npm Registry',
    group: 'global',
    probeType: 'fetch',
    url: 'https://registry.npmjs.org/react',
    logoUrl: 'https://www.npmjs.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Package',
    tags: ['JavaScript', '包源'],
    emphasis: '适合观察 npm registry 这类前端依赖更新源的触达表现。',
  },
  {
    id: 'npmjs-home',
    label: 'npm',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.npmjs.com/',
    logoUrl: 'https://www.npmjs.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Package',
    tags: ['JavaScript', '包管理'],
    emphasis: '适合补充 npm 网站入口与包信息页面的访问观察。',
  },
  {
    id: 'nodejs-home',
    label: 'Node.js',
    group: 'global',
    probeType: 'fetch',
    url: 'https://nodejs.org/',
    logoUrl: 'https://nodejs.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Runtime',
    tags: ['JavaScript', '下载'],
    emphasis: '适合观察 Node.js 运行时官网与下载入口的访问表现。',
  },
  {
    id: 'rust-lang-home',
    label: 'Rust',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.rust-lang.org/tools/install',
    logoUrl: 'https://www.rust-lang.org/static/images/favicon.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Runtime',
    tags: ['Rust', '安装'],
    emphasis: '适合观察 Rust 工具链安装入口的基础可达性。',
  },
  {
    id: 'crates-io',
    label: 'crates.io',
    group: 'global',
    probeType: 'fetch',
    url: 'https://crates.io/',
    logoUrl: 'https://crates.io/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Package',
    tags: ['Rust', '包源'],
    emphasis: '适合补充 Rust crate registry 的访问表现观察。',
  },
  {
    id: 'static-rust-lang',
    label: 'Rust Static',
    group: 'global',
    probeType: 'fetch',
    url: 'https://static.rust-lang.org/dist/channel-rust-stable.toml',
    logoUrl: 'https://www.rust-lang.org/static/images/favicon.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Update',
    tags: ['Rust', '更新源'],
    emphasis: '适合观察 rustup 默认更新元数据入口的可达性。',
  },
  {
    id: 'deno-home',
    label: 'Deno',
    group: 'global',
    probeType: 'fetch',
    url: 'https://deno.com/',
    logoUrl: 'https://deno.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Runtime',
    tags: ['JavaScript', '运行时'],
    emphasis: '适合补充现代 JavaScript 运行时服务入口的访问观察。',
  },
  {
    id: 'bun-home',
    label: 'Bun',
    group: 'global',
    probeType: 'fetch',
    url: 'https://bun.sh/',
    logoUrl: 'https://bun.sh/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Runtime',
    tags: ['JavaScript', '运行时'],
    emphasis: '适合观察 Bun 官网与安装入口的触达表现。',
  },
  {
    id: 'mdn-home',
    label: 'MDN',
    group: 'global',
    probeType: 'fetch',
    url: 'https://developer.mozilla.org/',
    logoUrl: 'https://developer.mozilla.org/favicon-48x48.cbbd161b.png',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Docs',
    tags: ['Web', '文档'],
    emphasis: '适合观察 Web 标准文档入口的访问质量。',
  },
  {
    id: 'docker-hub',
    label: 'Docker Hub',
    group: 'global',
    probeType: 'fetch',
    url: 'https://hub.docker.com/',
    logoUrl: 'https://www.docker.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Registry',
    tags: ['容器', '镜像源'],
    emphasis: '适合观察容器镜像生态入口的浏览器侧可达性。',
  },
  {
    id: 'kubernetes-docs',
    label: 'Kubernetes',
    group: 'global',
    probeType: 'fetch',
    url: 'https://kubernetes.io/docs/',
    logoUrl: 'https://kubernetes.io/icons/favicon-64.png',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Docs',
    tags: ['云原生', '文档'],
    emphasis: '适合补充 Kubernetes 文档入口与云原生资料访问观察。',
  },
  {
    id: 'steam-store',
    label: 'Steam',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://store.steampowered.com/',
    logoUrl: 'https://store.steampowered.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Game Store',
    tags: ['游戏平台', '商店'],
    emphasis: '适合观察 Steam 商店入口与游戏下载生态的基础可达性。',
  },
  {
    id: 'steam-community',
    label: 'Steam Community',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://steamcommunity.com/',
    logoUrl: 'https://steamcommunity.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Game Community',
    tags: ['游戏平台', '社区'],
    emphasis: '适合补充 Steam 社区入口的网络触达观察。',
  },
  {
    id: 'epic-games',
    label: 'Epic Games',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://store.epicgames.com/',
    logoUrl: 'https://store.epicgames.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Game Store',
    tags: ['游戏平台', '商店'],
    emphasis: '适合观察 Epic Games Store 入口的访问表现。',
  },
  {
    id: 'playstation',
    label: 'PlayStation',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.playstation.com/',
    logoUrl: 'https://www.playstation.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Console',
    tags: ['主机', '游戏平台'],
    emphasis: '适合观察 PlayStation 官网与服务入口的基础可达性。',
  },
  {
    id: 'xbox',
    label: 'Xbox',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.xbox.com/',
    logoUrl: 'https://www.xbox.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Console',
    tags: ['主机', '微软'],
    emphasis: '适合观察 Xbox 服务入口与微软游戏生态访问表现。',
  },
  {
    id: 'nintendo',
    label: 'Nintendo',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.nintendo.com/',
    logoUrl: 'https://www.nintendo.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Console',
    tags: ['主机', '任天堂'],
    emphasis: '适合观察 Nintendo 官网入口的访问质量。',
  },
  {
    id: 'twitch',
    label: 'Twitch',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.twitch.tv/',
    logoUrl: 'https://www.twitch.tv/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Streaming',
    tags: ['直播', '游戏社区'],
    emphasis: '适合观察游戏直播与社区入口的触达性。',
  },
  {
    id: 'roblox',
    label: 'Roblox',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.roblox.com/',
    logoUrl: 'https://www.roblox.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Game Platform',
    tags: ['游戏平台', 'UGC'],
    emphasis: '适合观察 Roblox 这类 UGC 游戏平台入口的访问表现。',
  },
  {
    id: 'riot-games',
    label: 'Riot Games',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.riotgames.com/',
    logoUrl: 'https://www.riotgames.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Publisher',
    tags: ['游戏厂商', '电竞'],
    emphasis: '适合观察 Riot Games 官网与电竞游戏生态入口。',
  },
  {
    id: 'ea',
    label: 'EA',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.ea.com/',
    logoUrl: 'https://www.ea.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Publisher',
    tags: ['游戏厂商', '发行'],
    emphasis: '适合观察 EA 游戏发行服务入口的访问表现。',
  },
  {
    id: 'battle-net',
    label: 'Battle.net',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.blizzard.com/',
    logoUrl: 'https://www.blizzard.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Game Platform',
    tags: ['游戏平台', '暴雪'],
    emphasis: '适合观察 Battle.net / Blizzard 游戏生态入口的可达性。',
  },
  {
    id: 'ubisoft',
    label: 'Ubisoft',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.ubisoft.com/',
    logoUrl: 'https://www.ubisoft.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Publisher',
    tags: ['游戏厂商', '发行'],
    emphasis: '适合补充 Ubisoft 官网与游戏服务入口访问观察。',
  },
  {
    id: 'mihoyo',
    label: 'miHoYo',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.mihoyo.com/',
    logoUrl: 'https://www.mihoyo.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'CN · Publisher',
    tags: ['游戏厂商', '中国'],
    emphasis: '适合观察米哈游官网入口的基础访问表现。',
  },
  {
    id: 'hoyoverse',
    label: 'HoYoverse',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.hoyoverse.com/',
    logoUrl: 'https://www.hoyoverse.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Publisher',
    tags: ['游戏厂商', '全球发行'],
    emphasis: '适合观察 HoYoverse 全球发行入口的访问表现。',
  },
  {
    id: 'netease-games',
    label: 'NetEase Games',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.neteasegames.com/',
    logoUrl: 'https://www.neteasegames.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Publisher',
    tags: ['游戏厂商', '中国'],
    emphasis: '适合观察网易游戏全球官网入口的访问表现。',
  },
  {
    id: 'tencent-games',
    label: 'Tencent Games',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://game.qq.com/',
    logoUrl: '/brand-logos/tencent.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'CN · Publisher',
    tags: ['游戏厂商', '中国'],
    emphasis: '适合观察腾讯游戏国内入口的访问质量。',
  },
  {
    id: 'wegame',
    label: 'WeGame',
    group: 'gaming',
    probeType: 'fetch',
    url: 'https://www.wegame.com.cn/',
    logoUrl: '/brand-logos/tencent.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'CN · Game Store',
    tags: ['游戏平台', '中国'],
    emphasis: '适合补充 WeGame 平台入口的浏览器侧触达观察。',
  },
  {
    id: 'gitlab-home',
    label: 'GitLab',
    group: 'global',
    probeType: 'fetch',
    url: 'https://gitlab.com/',
    logoUrl: 'https://gitlab.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Dev',
    tags: ['代码托管', 'CI'],
    emphasis: '适合观察 GitLab 代码托管与 CI 服务入口的连通性。',
  },
  {
    id: 'mit-home',
    label: 'MIT',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.mit.edu/',
    logoUrl: 'https://www.mit.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '美国'],
    emphasis: '适合观察 MIT 官网入口的国际学术网络访问表现。',
  },
  {
    id: 'stanford-home',
    label: 'Stanford',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.stanford.edu/',
    logoUrl: 'https://www.stanford.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '美国'],
    emphasis: '适合观察 Stanford 官网入口的国际学术网络访问表现。',
  },
  {
    id: 'harvard-home',
    label: 'Harvard',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.harvard.edu/',
    logoUrl: 'https://www.harvard.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '美国'],
    emphasis: '适合观察 Harvard 官网入口的国际学术网络访问表现。',
  },
  {
    id: 'berkeley-home',
    label: 'UC Berkeley',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.berkeley.edu/',
    logoUrl: 'https://www.berkeley.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '美国'],
    emphasis: '适合观察 UC Berkeley 官网入口的访问质量。',
  },
  {
    id: 'caltech-home',
    label: 'Caltech',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.caltech.edu/',
    logoUrl: 'https://www.caltech.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '科研'],
    emphasis: '适合观察 Caltech 官网入口的访问质量。',
  },
  {
    id: 'princeton-home',
    label: 'Princeton',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.princeton.edu/',
    logoUrl: 'https://www.princeton.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '美国'],
    emphasis: '适合观察 Princeton 官网入口的访问质量。',
  },
  {
    id: 'yale-home',
    label: 'Yale',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.yale.edu/',
    logoUrl: 'https://www.yale.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '美国'],
    emphasis: '适合观察 Yale 官网入口的访问质量。',
  },
  {
    id: 'columbia-home',
    label: 'Columbia University',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.columbia.edu/',
    logoUrl: 'https://www.columbia.edu/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · University',
    tags: ['高校', '美国'],
    emphasis: '适合观察 Columbia 官网入口的访问质量。',
  },
  {
    id: 'oxford-home',
    label: 'Oxford',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.ox.ac.uk/',
    logoUrl: 'https://www.ox.ac.uk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'UK · University',
    tags: ['高校', '英国'],
    emphasis: '适合观察 Oxford 官网入口的国际学术网络访问表现。',
  },
  {
    id: 'cambridge-home',
    label: 'Cambridge',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.cam.ac.uk/',
    logoUrl: 'https://www.cam.ac.uk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'UK · University',
    tags: ['高校', '英国'],
    emphasis: '适合观察 Cambridge 官网入口的国际学术网络访问表现。',
  },
  {
    id: 'imperial-home',
    label: 'Imperial College',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.imperial.ac.uk/',
    logoUrl: 'https://www.imperial.ac.uk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'UK · University',
    tags: ['高校', '英国'],
    emphasis: '适合观察 Imperial College 官网入口的访问质量。',
  },
  {
    id: 'ucl-home',
    label: 'UCL',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.ucl.ac.uk/',
    logoUrl: 'https://www.ucl.ac.uk/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'UK · University',
    tags: ['高校', '英国'],
    emphasis: '适合观察 UCL 官网入口的访问质量。',
  },
  {
    id: 'eth-home',
    label: 'ETH Zurich',
    group: 'global',
    probeType: 'fetch',
    url: 'https://ethz.ch/',
    logoUrl: 'https://ethz.ch/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'CH · University',
    tags: ['高校', '瑞士'],
    emphasis: '适合观察 ETH Zurich 官网入口的访问质量。',
  },
  {
    id: 'epfl-home',
    label: 'EPFL',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.epfl.ch/',
    logoUrl: 'https://www.epfl.ch/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'CH · University',
    tags: ['高校', '瑞士'],
    emphasis: '适合观察 EPFL 官网入口的访问质量。',
  },
  {
    id: 'u-tokyo-home',
    label: 'University of Tokyo',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.u-tokyo.ac.jp/',
    logoUrl: 'https://www.u-tokyo.ac.jp/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'JP · University',
    tags: ['高校', '日本'],
    emphasis: '适合观察东京大学官网入口的访问质量。',
  },
  {
    id: 'kyoto-u-home',
    label: 'Kyoto University',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.kyoto-u.ac.jp/',
    logoUrl: 'https://www.kyoto-u.ac.jp/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'JP · University',
    tags: ['高校', '日本'],
    emphasis: '适合观察京都大学官网入口的访问质量。',
  },
  {
    id: 'snu-home',
    label: 'Seoul National University',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.snu.ac.kr/',
    logoUrl: 'https://www.snu.ac.kr/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'KR · University',
    tags: ['高校', '韩国'],
    emphasis: '适合观察首尔大学官网入口的访问质量。',
  },
  {
    id: 'kaist-home',
    label: 'KAIST',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.kaist.ac.kr/',
    logoUrl: 'https://www.kaist.ac.kr/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'KR · University',
    tags: ['高校', '韩国'],
    emphasis: '适合观察 KAIST 官网入口的访问质量。',
  },
  {
    id: 'nus-home',
    label: 'NUS',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.nus.edu.sg/',
    logoUrl: 'https://www.nus.edu.sg/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'SG · University',
    tags: ['高校', '新加坡'],
    emphasis: '适合观察新加坡国立大学官网入口的访问质量。',
  },
  {
    id: 'ntu-sg-home',
    label: 'NTU Singapore',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.ntu.edu.sg/',
    logoUrl: 'https://www.ntu.edu.sg/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'SG · University',
    tags: ['高校', '新加坡'],
    emphasis: '适合观察南洋理工大学官网入口的访问质量。',
  },
  {
    id: 'cern-home',
    label: 'CERN',
    group: 'global',
    probeType: 'fetch',
    url: 'https://home.cern/',
    logoUrl: 'https://home.cern/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'CH · Research',
    tags: ['科研机构', '物理'],
    emphasis: '适合观察 CERN 官网入口的国际科研网络访问表现。',
  },
  {
    id: 'max-planck-home',
    label: 'Max Planck Society',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.mpg.de/',
    logoUrl: 'https://www.mpg.de/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'DE · Research',
    tags: ['科研机构', '德国'],
    emphasis: '适合观察 Max Planck Society 官网入口的访问质量。',
  },
  {
    id: 'nature-home',
    label: 'Nature',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.nature.com/',
    logoUrl: 'https://www.nature.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Publisher',
    tags: ['学术出版', '期刊'],
    emphasis: '适合观察 Nature 学术出版平台入口的访问表现。',
  },
  {
    id: 'science-home',
    label: 'Science',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.science.org/',
    logoUrl: 'https://www.science.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Publisher',
    tags: ['学术出版', '期刊'],
    emphasis: '适合观察 Science / AAAS 学术出版入口的访问表现。',
  },
  {
    id: 'ieee-home',
    label: 'IEEE',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.ieee.org/',
    logoUrl: 'https://www.ieee.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Organization',
    tags: ['学会', '工程'],
    emphasis: '适合观察 IEEE 学术组织入口的访问表现。',
  },
  {
    id: 'acm-home',
    label: 'ACM',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.acm.org/',
    logoUrl: 'https://www.acm.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Organization',
    tags: ['学会', '计算机'],
    emphasis: '适合观察 ACM 学术组织入口的访问表现。',
  },
  {
    id: 'arxiv-home',
    label: 'arXiv',
    group: 'global',
    probeType: 'fetch',
    url: 'https://arxiv.org/',
    logoUrl: 'https://arxiv.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Preprint',
    tags: ['预印本', '论文'],
    emphasis: '适合观察 arXiv 预印本平台入口的访问表现。',
  },
  {
    id: 'orcid-home',
    label: 'ORCID',
    group: 'global',
    probeType: 'fetch',
    url: 'https://orcid.org/',
    logoUrl: 'https://orcid.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Academic ID',
    tags: ['学术身份', '组织'],
    emphasis: '适合观察 ORCID 学术身份服务入口的访问表现。',
  },
  {
    id: 'crossref-home',
    label: 'Crossref',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.crossref.org/',
    logoUrl: 'https://www.crossref.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · DOI',
    tags: ['DOI', '索引'],
    emphasis: '适合观察 Crossref DOI 基础设施入口的访问表现。',
  },
  {
    id: 'microsoft-learn',
    label: 'Microsoft Learn',
    group: 'global',
    probeType: 'fetch',
    url: 'https://learn.microsoft.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Microsoft',
    tags: ['微软', '文档'],
    emphasis: '适合观察 Microsoft 官方文档与学习入口的访问表现。',
  },
  {
    id: 'azure-portal',
    label: 'Azure Portal',
    group: 'global',
    probeType: 'fetch',
    url: 'https://portal.azure.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Microsoft',
    tags: ['Azure', '云平台'],
    emphasis: '适合观察 Azure 管理入口在当前链路下的基础触达。',
  },
  {
    id: 'office-home',
    label: 'Microsoft 365',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.office.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Microsoft',
    tags: ['Office', 'SaaS'],
    emphasis: '适合补充 Microsoft 365 办公入口的访问观察。',
  },
  {
    id: 'outlook-home',
    label: 'Outlook',
    group: 'global',
    probeType: 'fetch',
    url: 'https://outlook.live.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Microsoft',
    tags: ['邮箱', 'SaaS'],
    emphasis: '适合观察 Outlook Web 邮箱入口的基础可达性。',
  },
  {
    id: 'teams-home',
    label: 'Teams',
    group: 'global',
    probeType: 'fetch',
    url: 'https://teams.microsoft.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Microsoft',
    tags: ['协作', '会议'],
    emphasis: '适合补充 Teams 协作入口的访问表现观察。',
  },
  {
    id: 'onedrive-home',
    label: 'OneDrive',
    group: 'global',
    probeType: 'fetch',
    url: 'https://onedrive.live.com/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Microsoft',
    tags: ['存储', 'SaaS'],
    emphasis: '适合观察 OneDrive 文件服务入口的触达性。',
  },
  {
    id: 'linkedin-home',
    label: 'LinkedIn',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.linkedin.com/',
    logoUrl: 'https://www.linkedin.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Microsoft',
    tags: ['职场', '社交'],
    emphasis: '适合补充 LinkedIn 这类微软生态社交服务的访问观察。',
  },
  {
    id: 'google-cloud-home',
    label: 'Google Cloud',
    group: 'global',
    probeType: 'fetch',
    url: 'https://cloud.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['Google', '云平台'],
    emphasis: '适合观察 Google Cloud 主入口的访问表现。',
  },
  {
    id: 'firebase-home',
    label: 'Firebase',
    group: 'global',
    probeType: 'fetch',
    url: 'https://firebase.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['Google', '开发'],
    emphasis: '适合补充 Firebase 开发平台入口的触达观察。',
  },
  {
    id: 'colab-home',
    label: 'Google Colab',
    group: 'global',
    probeType: 'fetch',
    url: 'https://colab.research.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['AI', 'Notebook'],
    emphasis: '适合观察 Google Colab 数据科学与 AI Notebook 入口。',
  },
  {
    id: 'google-drive',
    label: 'Google Drive',
    group: 'global',
    probeType: 'fetch',
    url: 'https://drive.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['存储', 'Google'],
    emphasis: '适合补充 Google Drive 文件服务入口的可达性观察。',
  },
  {
    id: 'gmail-home',
    label: 'Gmail',
    group: 'global',
    probeType: 'fetch',
    url: 'https://mail.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['邮箱', 'Google'],
    emphasis: '适合观察 Gmail Web 入口在当前链路下的基础触达。',
  },
  {
    id: 'google-maps',
    label: 'Google Maps',
    group: 'global',
    probeType: 'fetch',
    url: 'https://maps.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['地图', 'Google'],
    emphasis: '适合补充 Google Maps 服务入口的连通性观察。',
  },
  {
    id: 'google-play',
    label: 'Google Play',
    group: 'global',
    probeType: 'fetch',
    url: 'https://play.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['应用商店', 'Google'],
    emphasis: '适合观察 Google Play 应用服务入口的访问表现。',
  },
  {
    id: 'google-translate',
    label: 'Google Translate',
    group: 'global',
    probeType: 'fetch',
    url: 'https://translate.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Google',
    tags: ['翻译', 'Google'],
    emphasis: '适合补充 Google Translate 工具服务入口的可达性。',
  },
  {
    id: 'cloudflare-radar',
    label: 'Cloudflare Radar',
    group: 'global',
    probeType: 'fetch',
    url: 'https://radar.cloudflare.com/',
    logoUrl: 'https://www.cloudflare.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · Internet Intel',
    tags: ['Cloudflare', '观测'],
    emphasis: '适合观察 Cloudflare 网络观测服务的入口连通性。',
  },
  {
    id: 'cloudflare-docs',
    label: 'Cloudflare Docs',
    group: 'global',
    probeType: 'fetch',
    url: 'https://developers.cloudflare.com/',
    logoUrl: 'https://www.cloudflare.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['Cloudflare', '文档'],
    emphasis: '适合补充 Cloudflare 开发者文档与边缘网络入口观察。',
  },
  {
    id: 'akamai-home',
    label: 'Akamai',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.akamai.com/',
    logoUrl: 'https://www.akamai.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['CDN', '边缘网络'],
    emphasis: '适合观察 Akamai 全球边缘网络官网入口的访问表现。',
  },
  {
    id: 'fastly-home',
    label: 'Fastly',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.fastly.com/',
    logoUrl: 'https://www.fastly.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['CDN', '边缘计算'],
    emphasis: '适合补充 Fastly 边缘平台入口的浏览器侧触达观察。',
  },
  {
    id: 'cloudfront-docs',
    label: 'CloudFront',
    group: 'global',
    probeType: 'fetch',
    url: 'https://aws.amazon.com/cloudfront/',
    logoUrl: 'https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['AWS', 'CDN'],
    emphasis: '适合观察 AWS CloudFront 服务入口的访问表现。',
  },
  {
    id: 'google-cloud-cdn',
    label: 'Google Cloud CDN',
    group: 'global',
    probeType: 'fetch',
    url: 'https://cloud.google.com/cdn',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['Google Cloud', 'CDN'],
    emphasis: '适合补充 Google Cloud CDN 服务入口的可达性观察。',
  },
  {
    id: 'azure-cdn',
    label: 'Azure CDN',
    group: 'global',
    probeType: 'fetch',
    url: 'https://azure.microsoft.com/products/cdn/',
    logoUrl: '/brand-logos/microsoft.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['Azure', 'CDN'],
    emphasis: '适合观察 Microsoft Azure CDN 入口的浏览器侧连通性。',
  },
  {
    id: 'cdn77-home',
    label: 'CDN77',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.cdn77.com/',
    logoUrl: 'https://www.cdn77.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['CDN', '媒体分发'],
    emphasis: '适合补充 CDN77 这类独立 CDN 服务入口的访问质量观察。',
  },
  {
    id: 'bunny-home',
    label: 'Bunny',
    group: 'global',
    probeType: 'fetch',
    url: 'https://bunny.net/',
    logoUrl: 'https://bunny.net/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['CDN', '边缘网络'],
    emphasis: '适合观察 Bunny CDN 与边缘网络入口的基础可达性。',
  },
  {
    id: 'jsdelivr-cdn',
    label: 'jsDelivr',
    group: 'global',
    probeType: 'fetch',
    url: 'https://cdn.jsdelivr.net/npm/react@19.1.0/package.json',
    logoUrl: 'https://www.jsdelivr.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['开源 CDN', '前端资源'],
    emphasis: '适合观察常用开源前端 CDN 资源节点的触达表现。',
  },
  {
    id: 'unpkg-cdn',
    label: 'unpkg',
    group: 'global',
    probeType: 'fetch',
    url: 'https://unpkg.com/react@19.1.0/package.json',
    logoUrl: 'https://unpkg.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['开源 CDN', '前端资源'],
    emphasis: '适合补充 unpkg 包分发入口的浏览器侧访问表现。',
  },
  {
    id: 'cdnjs-cdn',
    label: 'cdnjs',
    group: 'global',
    probeType: 'fetch',
    url: 'https://cdnjs.cloudflare.com/ajax/libs/react/19.1.0/cjs/react.production.min.js',
    logoUrl: 'https://cdnjs.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · CDN',
    tags: ['开源 CDN', 'Cloudflare'],
    emphasis: '适合观察 Cloudflare 承载的开源资源 CDN 节点触达表现。',
  },
  {
    id: 'huggingface-home',
    label: 'Hugging Face',
    group: 'global',
    probeType: 'fetch',
    url: 'https://huggingface.co/',
    logoUrl: 'https://huggingface.co/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · AI',
    tags: ['AI', '模型'],
    emphasis: '适合观察开源模型与 AI 社区平台的基础访问表现。',
  },
  {
    id: 'perplexity-home',
    label: 'Perplexity',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.perplexity.ai/',
    logoUrl: 'https://www.perplexity.ai/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · AI',
    tags: ['AI', '搜索'],
    emphasis: '适合补充 AI 搜索服务入口的触达性观察。',
  },
  {
    id: 'yahoo-japan-home',
    label: 'Yahoo Japan',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.yahoo.co.jp/',
    logoUrl: 'https://www.yahoo.co.jp/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'JP · Portal',
    tags: ['日本', '门户'],
    emphasis: '适合观察日本主流门户入口的访问质量。',
  },
  {
    id: 'nhk-home',
    label: 'NHK',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.nhk.or.jp/',
    logoUrl: 'https://www.nhk.or.jp/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'JP · News',
    tags: ['日本', '新闻'],
    emphasis: '适合补充日本公共媒体网站的连通性观察。',
  },
  {
    id: 'naver-home',
    label: 'Naver',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.naver.com/',
    logoUrl: 'https://www.naver.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'KR · Portal',
    tags: ['韩国', '门户'],
    emphasis: '适合观察韩国主流门户入口的访问质量。',
  },
  {
    id: 'kakao-home',
    label: 'Kakao',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.kakaocorp.com/',
    logoUrl: 'https://www.kakaocorp.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'KR · Platform',
    tags: ['韩国', '平台'],
    emphasis: '适合补充韩国通信与平台服务入口的可达性观察。',
  },
  {
    id: 'bbc-home',
    label: 'BBC',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.bbc.com/',
    logoUrl: 'https://www.bbc.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · News',
    tags: ['新闻', '媒体'],
    emphasis: '适合观察国际新闻媒体入口的访问表现。',
  },
  {
    id: 'reuters-home',
    label: 'Reuters',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.reuters.com/',
    logoUrl: 'https://www.reuters.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Global · News',
    tags: ['新闻', '财经'],
    emphasis: '适合补充国际新闻与财经媒体的网页触达观察。',
  },
  {
    id: 'cnn-home',
    label: 'CNN',
    group: 'global',
    probeType: 'fetch',
    url: 'https://www.cnn.com/',
    logoUrl: 'https://www.cnn.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'US · News',
    tags: ['新闻', '媒体'],
    emphasis: '适合观察美国主流新闻媒体入口的访问表现。',
  },
  {
    id: 'claude-home',
    label: 'Claude',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://claude.ai/manifest.json',
    logoUrl: '/brand-logos/claude.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · AI',
    tags: ['AI', '助手'],
    emphasis: '适合观察受区域链路影响时，Claude 静态入口是否仍能完成连通。',
  },
  {
    id: 'chatgpt-home',
    label: 'ChatGPT',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://chatgpt.com/',
    logoUrl: 'https://chatgpt.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · AI',
    tags: ['AI', '助手'],
    emphasis: '适合观察 ChatGPT Web 入口在当前链路下是否能完成浏览器侧触达。',
  },
  {
    id: 'gemini-home',
    label: 'Gemini',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://gemini.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · AI',
    tags: ['AI', 'Google'],
    emphasis: '适合补充 Google AI 服务入口的可达性观察。',
  },
  {
    id: 'poe-home',
    label: 'Poe',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://poe.com/',
    logoUrl: 'https://poe.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · AI',
    tags: ['AI', '助手'],
    emphasis: '适合观察聚合式 AI 助手服务的入口触达。',
  },
  {
    id: 'discord-home',
    label: 'Discord',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://discord.com/',
    logoUrl: '/brand-logos/discord.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Community',
    tags: ['社区', '通信'],
    emphasis: '适合补充实时社区与协作平台在当前链路下的到达性观察。',
  },
  {
    id: 'netflix-home',
    label: 'Netflix',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.netflix.com/',
    logoUrl: '/brand-logos/netflix.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Streaming',
    tags: ['流媒体', '娱乐'],
    emphasis: '适合补充国际流媒体服务在当前网络环境下的入口可达性观察。',
  },
  {
    id: 'google-favicon',
    label: 'Google',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Search',
    tags: ['搜索', '国际入口'],
    emphasis: '适合观察典型国际入口在当前链路下是否顺利完成响应。',
  },
  {
    id: 'google-scholar',
    label: 'Google Scholar',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://scholar.google.com/',
    logoUrl: 'https://scholar.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Academic',
    tags: ['学术', 'Google'],
    emphasis: '适合重点观察 Google Scholar 学术入口在当前网络下的可达性。',
  },
  {
    id: 'google-accounts',
    label: 'Google Accounts',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://accounts.google.com/',
    logoUrl: 'https://www.google.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Login',
    tags: ['登录', 'Google'],
    emphasis: '适合观察 Google 登录入口这类更容易触发额外校验的路径。',
  },
  {
    id: 'youtube-favicon',
    label: 'YouTube',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.youtube.com/',
    logoUrl: '/brand-logos/youtube.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Video',
    tags: ['视频', '媒体'],
    emphasis: '适合观察媒体类国际服务的资源触达情况。',
  },
  {
    id: 'tiktok-home',
    label: 'TikTok',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.tiktok.com/',
    logoUrl: 'https://www.tiktok.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Short Video',
    tags: ['短视频', '社交'],
    emphasis: '适合观察 TikTok Web 入口在当前链路下的触达性。',
  },
  {
    id: 'facebook-home',
    label: 'Facebook',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.facebook.com/',
    logoUrl: 'https://www.facebook.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Social',
    tags: ['Meta', '社交'],
    emphasis: '适合观察 Facebook 入口及 Meta 社交链路的基础可达性。',
  },
  {
    id: 'instagram-home',
    label: 'Instagram',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.instagram.com/',
    logoUrl: 'https://www.instagram.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Social',
    tags: ['Meta', '图片'],
    emphasis: '适合补充 Instagram 入口在当前网络里的访问表现。',
  },
  {
    id: 'instagram-reels',
    label: 'Instagram Reels',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.instagram.com/reels/',
    logoUrl: 'https://www.instagram.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Short Video',
    tags: ['Meta', 'Reels'],
    emphasis: '适合观察 Reels 短视频入口是否能完成浏览器侧触达。',
  },
  {
    id: 'threads-home',
    label: 'Threads',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.threads.net/',
    logoUrl: 'https://www.threads.net/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Social',
    tags: ['Meta', '社交'],
    emphasis: '适合补充 Threads 文本社交入口的可达性观察。',
  },
  {
    id: 'whatsapp-home',
    label: 'WhatsApp',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.whatsapp.com/',
    logoUrl: 'https://www.whatsapp.com/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Messaging',
    tags: ['Meta', '通信'],
    emphasis: '适合观察 WhatsApp Web 生态入口的基础连通性。',
  },
  {
    id: 'signal-home',
    label: 'Signal',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://signal.org/',
    logoUrl: 'https://signal.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Messaging',
    tags: ['通信', '隐私'],
    emphasis: '适合补充加密通信服务官网入口的可达性观察。',
  },
  {
    id: 'telegram-web',
    label: 'Telegram',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://web.telegram.org/',
    logoUrl: 'https://web.telegram.org/favicon.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Messaging',
    tags: ['通信', 'Web'],
    emphasis: '适合补充即时通信类 Web 服务的到达性观察。',
  },
  {
    id: 'x-favicon',
    label: 'X',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://x.com/',
    logoUrl: 'https://abs.twimg.com/favicons/twitter.3.ico',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Social',
    tags: ['社交', '实时信息'],
    emphasis: '适合观察社交入口的静态资源访问能力。',
  },
  {
    id: 'reddit-favicon',
    label: 'Reddit',
    group: 'challenge',
    probeType: 'fetch',
    url: 'https://www.reddit.com/',
    logoUrl: '/brand-logos/reddit.svg',
    timeoutMs: 7000,
    expectedSignal: 'opaque',
    location: 'Challenge · Community',
    tags: ['社区', '讨论'],
    emphasis: '适合补充国际讨论社区的访问情况。',
  }
]
